name: ci
run-name: 06 - Contexts | DEBUG - var=${{ vars.DB_USER }} and GitHub=${{ github.ref }} inputs=${{ inputs.debug && 'ON' || 'OFF'}}"

on:
  push:
  workflow_dispatch:
    inputs:      
      debug:
        description: wqweqweqw
        type: boolean
        default: true
        
env:
  MY_WORKFLOW_VAR: 'workflow'
  MY_OVERWRITTEN_VAR: 'workflow'
  MY_OVERWRITTEN_VAR2: 'workflow'
  DB_USER: ${{ vars.DB_USER || 'default_user' }}

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:

    - name: Display Event Information
      run: |
        echo "Event Name: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
        echo "SHA: ${{ github.sha }}"  

    - name: Retrieve Variable
      run: |
        echo "Variable value: ${{ vars.MY_VAR }}"  

    - name: Print Env Variables
      run: |
        echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
        echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"             

    - name: Print Env Variables-2
      env:
        MY_OVERWRITTEN_VAR: 'step'
      run: |
        echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
        echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"    

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Env Variables-3
        run: |
          echo "Workflow env: $MY_WORKFLOW_VAR"
          echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"                 