name: 11 - Working with Inputs

on: 
  push:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        default: false
        description: Skip deployment 
      target:
        type: environment
        required: true
        description: Which environment the workflow will target
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v3
        description: Release from which to build and deploy

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Build-step
        run: echo "Building from tag ${{ inputs.tag }}"

  deploy-job:
    runs-on: ubuntu-latest
    needs: build-job
    environment: ${{ inputs.target }}
    if: ${{ !inputs.dry-run }}
    steps:
      - name: Deploy-step
        run: echo "Deploying to ${{ inputs.target }}"