name: 11 - Working with Inputs

on: 
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        default: false
        description: Skip deployment and only print build output
      target-environment:
        type: environment
        required: true
        description: Which environment the workflow will target
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v3
        description: Release from which to build and deploy

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo step1
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo step1  