name: 12-outputs

on:
  push:
  workflow_dispatch:
    inputs:
      build-status:
        description: select status
        type: choice
        options:        
          - success
          - failure
        default: success  

jobs:
  build-job:
    runs-on: ubuntu-latest  
    outputs:
      build-status: ${{ steps.build.outputs.status }}
    steps:
      - name: build
        id: build
        run: echo "status=success" >> "$GITHUB_OUTPUT"

  deploy-job:
    runs-on: ubuntu-latest
    needs: build-job
    if: ${{ needs.build-job.build-status == 'success' }}
    steps:
      - name: deploy
        run: echo "Deploying ..."
  
