name: 12-outputs

on:
  push:
  workflow_dispatch:
    inputs:
      build-status:
        description: select status
        type: choice
        options:        
          - success
          - failure
        default: success  

jobs:
  build:
    runs-on: ubuntu-latest  
    outputs:
      build-status: ${{ steps.build.outputs.status }}
    steps:
      - name: Build 
        id: build
        run: |
          echo "status=success" >> "$GITHUB_OUTPUT"
          echo "============================================"
          cat "$GITHUB_OUTPUT"
          echo "============================================"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.build-status != 'success' }}
    steps:
      - name: Deploy
        run: echo "Deploying ..."
      
      - name: Print output        
        run: |
          echo "Output: ${{ needs.build.build-status }}"
  
